name: Bandit Scan

on: push

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bandit
        uses: shundor/python-bandit-scan@v1.0
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
